"""initial_schema

Revision ID: 031c74c6de97
Revises: 
Create Date: 2026-09-08 16:06:58.091684
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# 仅在 Postgres 方言下可用 pgvector
try:
    from pgvector.sqlalchemy import Vector
except ImportError:  # pragma: no cover
    Vector = None

revision: str = '031c74c6de97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decisions_run_id'), 'ai_decisions', ['run_id'], unique=False)
    op.create_index(op.f('ix_ai_decisions_tenant_id'), 'ai_decisions', ['tenant_id'], unique=False)
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('pipeline', sa.String(length=64), nullable=False),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRYING', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('model_tier', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('is_mock', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Float(), nullable=True),
    sa.Column('stage_counts', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_job_id'), 'ai_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_ref_id'), 'ai_runs', ['ref_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_tenant_id'), 'ai_runs', ['tenant_id'], unique=False)
    op.create_table('archive_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_versions_archive_id'), 'archive_versions', ['archive_id'], unique=False)
    op.create_index(op.f('ix_archive_versions_tenant_id'), 'archive_versions', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('case_analysis_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_analysis_versions_analysis_id'), 'case_analysis_versions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_case_analysis_versions_tenant_id'), 'case_analysis_versions', ['tenant_id'], unique=False)
    op.create_table('case_precedents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_no', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('court', sa.String(length=200), nullable=True),
    sa.Column('holding', sa.Text(), nullable=True),
    sa.Column('facts', sa.Text(), nullable=True),
    sa.Column('dispute_type', sa.String(length=100), nullable=True),
    sa.Column('related_laws', sa.String(length=500), nullable=True),
    sa.Column('judgment_date', sa.String(length=32), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_precedents_case_no'), 'case_precedents', ['case_no'], unique=False)
    op.create_index(op.f('ix_case_precedents_tenant_id'), 'case_precedents', ['tenant_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_no', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('client_user_id', sa.Integer(), nullable=True),
    sa.Column('lawyer_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('INTAKE', 'PENDING_DISPATCH', 'DISPATCHED', 'ACCEPTED', 'IN_REVIEW', 'CONFIRMED', 'ARCHIVED', 'CLOSED', 'VOIDED', name='casestatus', native_enum=False, length=32), nullable=False),
    sa.Column('intent', sa.Enum('CONSULT', 'DOCUMENT', 'CALCULATION', 'REVIEW', 'ENTRUST', name='intenttype', native_enum=False, length=32), nullable=True),
    sa.Column('grade', sa.Enum('S', 'A', 'B', 'C', name='casegrade', native_enum=False, length=8), nullable=False),
    sa.Column('dispute_type', sa.String(length=100), nullable=True),
    sa.Column('party_a', sa.String(length=200), nullable=True),
    sa.Column('party_b', sa.String(length=200), nullable=True),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('claim_amount', sa.Float(), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('require_formal_opinion', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], use_alter=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], use_alter=True),
    sa.ForeignKeyConstraint(['lawyer_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_no'), 'cases', ['case_no'], unique=True)
    op.create_index(op.f('ix_cases_lawyer_id'), 'cases', ['lawyer_id'], unique=False)
    op.create_index(op.f('ix_cases_tenant_id'), 'cases', ['tenant_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.Enum('LAW', 'CASE', 'TEMPLATE', 'KNOWLEDGE', name='citationsourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=300), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('authority', sa.String(length=200), nullable=True),
    sa.Column('effective_date', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('timeliness', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_tenant_id'), 'citations', ['tenant_id'], unique=False)
    op.create_table('compliance_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='scanstatus', native_enum=False, length=32), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('overall_risk', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('dimension_scores', sa.JSON(), nullable=True),
    sa.Column('report_summary', sa.Text(), nullable=True),
    sa.Column('is_external', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=True),
    sa.Column('finished_at', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_scans_tenant_id'), 'compliance_scans', ['tenant_id'], unique=False)
    op.create_table('contract_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('overall_risk', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_reviews_tenant_id'), 'contract_reviews', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('client_user_id', sa.Integer(), nullable=True),
    sa.Column('external_user_id', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.Enum('WEB_SIM', 'WECOM', 'FEISHU', name='imchannel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('BOT', 'WAITING_HUMAN', 'HUMAN', 'CLOSED', name='conversationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('bind_lawyer_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('last_message_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bind_lawyer_id'], ['users.id'], use_alter=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], use_alter=True),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_external_user_id'), 'conversations', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('dispatch_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('candidate_lawyer_ids', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_rules_tenant_id'), 'dispatch_rules', ['tenant_id'], unique=False)
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('lifecycle', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_high_risk', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_lawyer', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_code'), 'document_templates', ['code'], unique=False)
    op.create_index(op.f('ix_document_templates_lifecycle'), 'document_templates', ['lifecycle'], unique=False)
    op.create_index(op.f('ix_document_templates_tenant_id'), 'document_templates', ['tenant_id'], unique=False)
    op.create_table('evidence_checklists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('dispute_type', sa.String(length=100), nullable=False),
    sa.Column('item', sa.String(length=300), nullable=False),
    sa.Column('category', sa.Enum('CONTRACT', 'PAYMENT', 'COMMUNICATION', 'IDENTITY', 'OFFICIAL', 'OTHER', name='evidencecategory', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_checklists_dispute_type'), 'evidence_checklists', ['dispute_type'], unique=False)
    op.create_index(op.f('ix_evidence_checklists_tenant_id'), 'evidence_checklists', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.Enum('CASE_ANALYSIS', 'EVIDENCE_PARSE', 'COMPLIANCE_SCAN', 'DOCUMENT_GEN', name='jobtype', native_enum=False, length=32), nullable=False),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRYING', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=True),
    sa.Column('step_state', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_ref_id'), 'jobs', ['ref_id'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('knowledge_docs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=300), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_lawyer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_docs_doc_type'), 'knowledge_docs', ['doc_type'], unique=False)
    op.create_index(op.f('ix_knowledge_docs_tenant_id'), 'knowledge_docs', ['tenant_id'], unique=False)
    op.create_table('knowledge_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536) if op.get_bind().dialect.name == 'postgresql' else sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_embeddings_doc_id'), 'knowledge_embeddings', ['doc_id'], unique=False)
    op.create_index(op.f('ix_knowledge_embeddings_tenant_id'), 'knowledge_embeddings', ['tenant_id'], unique=False)
    op.create_table('law_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('law_name', sa.String(length=300), nullable=False),
    sa.Column('article_no', sa.String(length=64), nullable=False),
    sa.Column('chapter', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('effective_date', sa.String(length=32), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('timeliness', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_articles_law_name'), 'law_articles', ['law_name'], unique=False)
    op.create_index(op.f('ix_law_articles_tenant_id'), 'law_articles', ['tenant_id'], unique=False)
    op.create_table('lawyer_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialties', sa.String(length=500), nullable=False),
    sa.Column('practice_years', sa.Integer(), nullable=False),
    sa.Column('license_no', sa.String(length=100), nullable=True),
    sa.Column('active_case_count', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('can_l3_review', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyer_profiles_tenant_id'), 'lawyer_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lawyer_profiles_user_id'), 'lawyer_profiles', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DISPATCH_CREATED', 'CASE_ACCEPTED', 'EVIDENCE_MISSING', 'REVIEW_REQUIRED', 'REVIEW_DECIDED', 'DOCUMENT_CONFIRMED', 'CASE_ARCHIVED', 'QUOTA_WARNING', 'WORK_ORDER_CREATED', name='notificationtype', native_enum=False, length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('review_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=64), nullable=True),
    sa.Column('level', sa.Enum('L1', 'L2', 'L3', name='reviewlevel', native_enum=False, length=8), nullable=True),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_records_review_id'), 'review_records', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_records_tenant_id'), 'review_records', ['tenant_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.Enum('CASE_ANALYSIS', 'DOCUMENT', 'EVIDENCE_LIST', 'COMPLIANCE_REPORT', 'LEGAL_OPINION', name='reviewtargettype', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'LAWYER_EDITING', 'PENDING_CONFIRM', 'CONFIRMED', 'ARCHIVED', 'VOIDED', name='reviewstatus', native_enum=False, length=32), nullable=False),
    sa.Column('required_level', sa.Enum('L1', 'L2', 'L3', name='reviewlevel', native_enum=False, length=8), nullable=False),
    sa.Column('satisfied_level', sa.Enum('L1', 'L2', 'L3', name='reviewlevel', native_enum=False, length=8), nullable=True),
    sa.Column('is_forced', sa.Integer(), nullable=False),
    sa.Column('forced_hits', sa.JSON(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'REVISION_REQUESTED', name='reviewdecision', native_enum=False, length=32), nullable=True),
    sa.Column('decided_at', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_case_id'), 'reviews', ['case_id'], unique=False)
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    op.create_index(op.f('ix_reviews_tenant_id'), 'reviews', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=32), nullable=False),
    sa.Column('end_date', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('PLATFORM', 'LAW_FIRM', 'ENTERPRISE', name='tenanttype', native_enum=False, length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('seat_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bot_welcome', sa.Text(), nullable=True),
    sa.Column('bot_disclaimer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    op.create_table('usage_quotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('usage_type', sa.Enum('QA', 'DOCUMENT', 'CONTRACT_REVIEW', 'COMPLIANCE_SCAN', name='usagetype', native_enum=False, length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('limit_count', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_quotas_period'), 'usage_quotas', ['period'], unique=False)
    op.create_index(op.f('ix_usage_quotas_tenant_id'), 'usage_quotas', ['tenant_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('usage_type', sa.Enum('QA', 'DOCUMENT', 'CONTRACT_REVIEW', 'COMPLIANCE_SCAN', name='usagetype', native_enum=False, length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('converted_to_work_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_period'), 'usage_records', ['period'], unique=False)
    op.create_index(op.f('ix_usage_records_tenant_id'), 'usage_records', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'FIRM_ADMIN', 'LAWYER', 'ASSISTANT', 'CLIENT', 'ENTERPRISE_ADMIN', 'ENTERPRISE_USER', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('im_channel', sa.String(length=32), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('usage_type', sa.Enum('QA', 'DOCUMENT', 'CONTRACT_REVIEW', 'COMPLIANCE_SCAN', name='usagetype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED', name='workorderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('urgent', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('escalate_to_lawyer', sa.Integer(), nullable=False),
    sa.Column('assigned_lawyer_id', sa.Integer(), nullable=True),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.String(length=64), nullable=True),
    sa.Column('billing_note', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_order_no'), 'work_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_work_orders_tenant_id'), 'work_orders', ['tenant_id'], unique=False)
    op.create_table('archives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('archive_no', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('dossier', sa.JSON(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('archived_by', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.String(length=64), nullable=True),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('hearing_pack_path', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archives_archive_no'), 'archives', ['archive_no'], unique=True)
    op.create_index(op.f('ix_archives_case_id'), 'archives', ['case_id'], unique=True)
    op.create_index(op.f('ix_archives_tenant_id'), 'archives', ['tenant_id'], unique=False)
    op.create_table('case_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('legal_analysis', sa.Text(), nullable=True),
    sa.Column('related_laws', sa.JSON(), nullable=True),
    sa.Column('similar_cases', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('missing_info', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'LAWYER_EDITING', 'PENDING_CONFIRM', 'CONFIRMED', 'ARCHIVED', 'VOIDED', name='reviewstatus', native_enum=False, length=32), nullable=False),
    sa.Column('required_level', sa.Enum('L1', 'L2', 'L3', name='reviewlevel', native_enum=False, length=8), nullable=False),
    sa.Column('forced_hits', sa.JSON(), nullable=True),
    sa.Column('ai_generated', sa.Integer(), nullable=False),
    sa.Column('iteration_notes', sa.JSON(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_analyses_case_id'), 'case_analyses', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_analyses_tenant_id'), 'case_analyses', ['tenant_id'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.String(length=64), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_events_tenant_id'), 'case_events', ['tenant_id'], unique=False)
    op.create_table('compliance_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.Enum('LABOR', 'COMMERCIAL', 'DATA_PRIVACY', 'ADVERTISING', name='compliancedimension', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('citation_ids', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['compliance_scans.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_findings_scan_id'), 'compliance_findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_compliance_findings_tenant_id'), 'compliance_findings', ['tenant_id'], unique=False)
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('DESIGNATED', 'AUTO', 'POOL', name='dispatchmode', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='dispatchstatus', native_enum=False, length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], use_alter=True),
    sa.ForeignKeyConstraint(['lawyer_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_case_id'), 'dispatches', ['case_id'], unique=False)
    op.create_index(op.f('ix_dispatches_lawyer_id'), 'dispatches', ['lawyer_id'], unique=False)
    op.create_index(op.f('ix_dispatches_tenant_id'), 'dispatches', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COLLECTING', 'GENERATED', 'IN_REVIEW', 'CONFIRMED', 'EXPORTED', 'VOIDED', name='documentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('missing_variables', sa.JSON(), nullable=True),
    sa.Column('risk_findings', sa.JSON(), nullable=True),
    sa.Column('overall_risk', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('review_status', sa.Enum('DRAFT', 'LAWYER_EDITING', 'PENDING_CONFIRM', 'CONFIRMED', 'ARCHIVED', 'VOIDED', name='reviewstatus', native_enum=False, length=32), nullable=False),
    sa.Column('required_level', sa.Enum('L1', 'L2', 'L3', name='reviewlevel', native_enum=False, length=8), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.String(length=64), nullable=True),
    sa.Column('export_path', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], use_alter=True),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'PARSED', 'FAILED', name='evidencestatus', native_enum=False, length=32), nullable=False),
    sa.Column('category', sa.Enum('CONTRACT', 'PAYMENT', 'COMMUNICATION', 'IDENTITY', 'OFFICIAL', 'OTHER', name='evidencecategory', native_enum=False, length=32), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('legality_risks', sa.JSON(), nullable=True),
    sa.Column('event_date', sa.String(length=64), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_case_id'), 'evidences', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidences_tenant_id'), 'evidences', ['tenant_id'], unique=False)
    op.create_table('hearing_packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hearing_packs_case_id'), 'hearing_packs', ['case_id'], unique=False)
    op.create_index(op.f('ix_hearing_packs_tenant_id'), 'hearing_packs', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Enum('CLIENT', 'AI', 'LAWYER', 'SYSTEM', name='messagesender', native_enum=False, length=32), nullable=False),
    sa.Column('msg_type', sa.Enum('TEXT', 'IMAGE', 'FILE', 'VOICE', 'VIDEO', 'CARD', 'EVENT', name='messagetype', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('card_payload', sa.JSON(), nullable=True),
    sa.Column('citation_ids', sa.JSON(), nullable=True),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='租户标识，业务表按此字段逻辑隔离'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_hearing_packs_tenant_id'), table_name='hearing_packs')
    op.drop_index(op.f('ix_hearing_packs_case_id'), table_name='hearing_packs')
    op.drop_table('hearing_packs')
    op.drop_index(op.f('ix_evidences_tenant_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_case_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_dispatches_tenant_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_lawyer_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_case_id'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_index(op.f('ix_compliance_findings_tenant_id'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_scan_id'), table_name='compliance_findings')
    op.drop_table('compliance_findings')
    op.drop_index(op.f('ix_case_events_tenant_id'), table_name='case_events')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_case_analyses_tenant_id'), table_name='case_analyses')
    op.drop_index(op.f('ix_case_analyses_case_id'), table_name='case_analyses')
    op.drop_table('case_analyses')
    op.drop_index(op.f('ix_archives_tenant_id'), table_name='archives')
    op.drop_index(op.f('ix_archives_case_id'), table_name='archives')
    op.drop_index(op.f('ix_archives_archive_no'), table_name='archives')
    op.drop_table('archives')
    op.drop_index(op.f('ix_work_orders_tenant_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_order_no'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_records_tenant_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_period'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_usage_quotas_tenant_id'), table_name='usage_quotas')
    op.drop_index(op.f('ix_usage_quotas_period'), table_name='usage_quotas')
    op.drop_table('usage_quotas')
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_reviews_tenant_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_case_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_review_records_tenant_id'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_review_id'), table_name='review_records')
    op.drop_table('review_records')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_lawyer_profiles_user_id'), table_name='lawyer_profiles')
    op.drop_index(op.f('ix_lawyer_profiles_tenant_id'), table_name='lawyer_profiles')
    op.drop_table('lawyer_profiles')
    op.drop_index(op.f('ix_law_articles_tenant_id'), table_name='law_articles')
    op.drop_index(op.f('ix_law_articles_law_name'), table_name='law_articles')
    op.drop_table('law_articles')
    op.drop_index(op.f('ix_knowledge_embeddings_tenant_id'), table_name='knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_embeddings_doc_id'), table_name='knowledge_embeddings')
    op.drop_table('knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_docs_tenant_id'), table_name='knowledge_docs')
    op.drop_index(op.f('ix_knowledge_docs_doc_type'), table_name='knowledge_docs')
    op.drop_table('knowledge_docs')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_ref_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_evidence_checklists_tenant_id'), table_name='evidence_checklists')
    op.drop_index(op.f('ix_evidence_checklists_dispute_type'), table_name='evidence_checklists')
    op.drop_table('evidence_checklists')
    op.drop_index(op.f('ix_document_templates_tenant_id'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_lifecycle'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_code'), table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_index(op.f('ix_dispatch_rules_tenant_id'), table_name='dispatch_rules')
    op.drop_table('dispatch_rules')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_external_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_contract_reviews_tenant_id'), table_name='contract_reviews')
    op.drop_table('contract_reviews')
    op.drop_index(op.f('ix_compliance_scans_tenant_id'), table_name='compliance_scans')
    op.drop_table('compliance_scans')
    op.drop_index(op.f('ix_citations_tenant_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_cases_tenant_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_lawyer_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_no'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_case_precedents_tenant_id'), table_name='case_precedents')
    op.drop_index(op.f('ix_case_precedents_case_no'), table_name='case_precedents')
    op.drop_table('case_precedents')
    op.drop_index(op.f('ix_case_analysis_versions_tenant_id'), table_name='case_analysis_versions')
    op.drop_index(op.f('ix_case_analysis_versions_analysis_id'), table_name='case_analysis_versions')
    op.drop_table('case_analysis_versions')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_archive_versions_tenant_id'), table_name='archive_versions')
    op.drop_index(op.f('ix_archive_versions_archive_id'), table_name='archive_versions')
    op.drop_table('archive_versions')
    op.drop_index(op.f('ix_ai_runs_tenant_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_ref_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_job_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_ai_decisions_tenant_id'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_run_id'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    # ### end Alembic commands ###
